# A Revision to pandas DataFrames

In [1]:
import pandas as pd
import numpy as np

In [2]:
array_a = np.array([[3,2,1], [6,3,2]])
array_a

array([[3, 2, 1],
       [6, 3, 2]])

In [3]:
pd.DataFrame(array_a)

   0  1  2
0  3  2  1
1  6  3  2

In [14]:
type(pd.DataFrame(array_a))

pandas.core.frame.DataFrame

In [15]:
df = pd.DataFrame(array_a, columns = ['Column 1', 'Column 2', ' Column 3'])
df

   Column 1  Column 2   Column 3
0         3         2          1
1         6         3          2

In [16]:
df = pd.DataFrame(array_a, columns = ['Column 1', 'Column 2', ' Column 3'], index=['Row 1', 'Row 2'])
df

       Column 1  Column 2   Column 3
Row 1         3         2          1
Row 2         6         3          2

## Exercise 116

In [17]:
import pandas as pd

data = [['Amy White', 50, 5], 
        ['Jack Stewart',53,8],
        ['Richard Lauderdale', 35, 3],
        ['Sara Johnson', 43, 10]] 


df = pd.DataFrame(data, columns =['Name', 'Age', 'Working Experience (Yrs.)'])
print (df)

                 Name  Age  Working Experience (Yrs.)
0           Amy White   50                          5
1        Jack Stewart   53                          8
2  Richard Lauderdale   35                          3
3        Sara Johnson   43                         10

## Exercise 117

In [22]:
import pandas as pd

data = {
    "Name":['Amy White', 'Jack Stewart', 'Richard Lauderdale', 'Sara Johnson'], 
    "Age":[50, 53, 35, 43], 
    "Working Experience (Yrs.)":[5,8,3,10]}
df = pd.DataFrame(data, index = [1,2,3,4])
print (df)

                 Name  Age  Working Experience (Yrs.)
1           Amy White   50                          5
2        Jack Stewart   53                          8
3  Richard Lauderdale   35                          3
4        Sara Johnson   43                         10

## Exercise 126
Print the data types of the values stored in each column

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)

data = pd.read_csv('Sales-products-100.csv')
sales_products_data = data.copy()

print (sales_products_data.dtypes)

# Data Selection

In [1]:
import pandas as pd

In [5]:
data = pd.read_csv('Exercise\Dataset\Lending-company.csv', index_col= 'StringID')
lending_co_data = data.copy()
lending_co_data.head()

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_1,1,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
LoanID_3,3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
LoanID_4,4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
LoanID_5,5,Product B,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active

In [ ]:
# Access the information of a specific column
lending_co_data.Product

StringID
LoanID_1       Product B
LoanID_2       Product D
LoanID_3       Product B
LoanID_4       Product A
LoanID_5       Product B
                 ...
LoanID_1039    Product B
LoanID_1040    Product A
LoanID_1041    Product A
LoanID_1042    Product B
LoanID_1043    Product A
Name: Product, Length: 1043, dtype: object

In [ ]:
# Access the information of a specific column
lending_co_data.Location

In [ ]:
# Access the information of a specific column
lending_co_data['Product']

StringID
LoanID_1       Product B
LoanID_2       Product D
LoanID_3       Product B
LoanID_4       Product A
LoanID_5       Product B
                 ...
LoanID_1039    Product B
LoanID_1040    Product A
LoanID_1041    Product A
LoanID_1042    Product B
LoanID_1043    Product A
Name: Product, Length: 1043, dtype: object

In [ ]:
# Access the information of a specific column
lending_co_data['Location']

In [11]:
type(lending_co_data['Location'])

pandas.core.series.Series

In [ ]:
# Obtain a dataframe from a single column of a dataframe
lending_co_data[['Location']]

                Location
StringID
LoanID_1      Location 3
LoanID_2      Location 6
LoanID_3      Location 8
LoanID_4     Location 26
LoanID_5     Location 34
...                  ...
LoanID_1039  Location 73
LoanID_1040  Location 82
LoanID_1041  Location 11
LoanID_1042  Location 26
LoanID_1043  Location 94

[1043 rows x 1 columns]

In [12]:
type(lending_co_data[['Location']])

pandas.core.frame.DataFrame

In [13]:
lending_co_data[['Location','Product']].head()

             Location    Product
StringID
LoanID_1   Location 3  Product B
LoanID_2   Location 6  Product D
LoanID_3   Location 8  Product B
LoanID_4  Location 26  Product A
LoanID_5  Location 34  Product B

In [14]:
prod_loc = ['Location', 'Product']
lending_co_data[prod_loc].head()

             Location    Product
StringID
LoanID_1   Location 3  Product B
LoanID_2   Location 6  Product D
LoanID_3   Location 8  Product B
LoanID_4  Location 26  Product A
LoanID_5  Location 34  Product B

In [ ]:
# Expected Error:
lending_co_data['Product', 'Location']

KeyError: ('Product', 'Location')

In [16]:
lending_co_data[['Product', 'Location']]

               Product     Location
StringID
LoanID_1     Product B   Location 3
LoanID_2     Product D   Location 6
LoanID_3     Product B   Location 8
LoanID_4     Product A  Location 26
LoanID_5     Product B  Location 34
...                ...          ...
LoanID_1039  Product B  Location 73
LoanID_1040  Product A  Location 82
LoanID_1041  Product A  Location 11
LoanID_1042  Product B  Location 26
LoanID_1043  Product A  Location 94

[1043 rows x 2 columns]

In [20]:
print (lending_co_data['Product'].dtypes)

object

## Data Selection with pn.iloc[]

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html

In [21]:
import pandas as pd

In [22]:
data = pd.read_csv('Exercise\Dataset\Lending-company.csv', index_col= 'StringID')
lending_co_data = data.copy()
lending_co_data.head()

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_1,1,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
LoanID_3,3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
LoanID_4,4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
LoanID_5,5,Product B,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active

In [23]:
lending_co_data[1]

KeyError: 1

In [24]:
lending_co_data['Product']

StringID
LoanID_1       Product B
LoanID_2       Product D
LoanID_3       Product B
LoanID_4       Product A
LoanID_5       Product B
                 ...
LoanID_1039    Product B
LoanID_1040    Product A
LoanID_1041    Product A
LoanID_1042    Product B
LoanID_1043    Product A
Name: Product, Length: 1043, dtype: object

In [ ]:
# Obtain the information of the first row
lending_co_data.iloc[1]

LoanID                     2
Product            Product D
CustomerGender        Female
Location          Location 6
Region              Region 6
TotalPrice               NaN
StartDate         02/01/2019
Deposit                 2200
DailyRate                 45
TotalDaysYr              365
AmtPaid36               3161
AmtPaid60               4096
AmtPaid360             16041
LoanStatus            Active
Name: LoanID_2, dtype: object

In [27]:
# info of a specific location in the dataframe, (row 1, column 3)
lending_co_data.iloc[1, 3]

'Location 6'

In [ ]:
# Obtain information of all the values in a specific row
lending_co_data.iloc[1,:]

LoanID                     2
Product            Product D
CustomerGender        Female
Location          Location 6
Region              Region 6
TotalPrice               NaN
StartDate         02/01/2019
Deposit                 2200
DailyRate                 45
TotalDaysYr              365
AmtPaid36               3161
AmtPaid60               4096
AmtPaid360             16041
LoanStatus            Active
Name: LoanID_2, dtype: object

In [ ]:
# Obtain information of all the values in a specific column
lending_co_data.iloc[:,3]

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [30]:
type(lending_co_data.iloc[1,3])

str

In [31]:
type(lending_co_data.iloc[1,:])

pandas.core.series.Series

In [32]:
type(lending_co_data.iloc[:,3])

pandas.core.series.Series

In [ ]:
# Access several sets of data
lending_co_data.iloc[[1,3],:]

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
LoanID_4,4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active

In [34]:
lending_co_data.iloc[:,[1,3]]

               Product     Location
StringID
LoanID_1     Product B   Location 3
LoanID_2     Product D   Location 6
LoanID_3     Product B   Location 8
LoanID_4     Product A  Location 26
LoanID_5     Product B  Location 34
...                ...          ...
LoanID_1039  Product B  Location 73
LoanID_1040  Product A  Location 82
LoanID_1041  Product A  Location 11
LoanID_1042  Product B  Location 26
LoanID_1043  Product A  Location 94

[1043 rows x 2 columns]

## Data Selection pn.loc[]

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('Exercise\Dataset\Lending-company.csv', index_col= 'StringID')
lending_co_data = data.copy()
lending_co_data.head()

In [35]:
lending_co_data.loc['LoanID_3']

LoanID                     3
Product            Product B
CustomerGender          Male
Location          Location 8
Region              Region 3
TotalPrice           16600.0
StartDate         08/12/2016
Deposit                 1000
DailyRate                 45
TotalDaysYr              365
AmtPaid36               2260
AmtPaid60               3205
AmtPaid360             16340
LoanStatus               NaN
Name: LoanID_3, dtype: object

In [36]:
lending_co_data.loc['LoanID_3', :]

LoanID                     3
Product            Product B
CustomerGender          Male
Location          Location 8
Region              Region 3
TotalPrice           16600.0
StartDate         08/12/2016
Deposit                 1000
DailyRate                 45
TotalDaysYr              365
AmtPaid36               2260
AmtPaid60               3205
AmtPaid360             16340
LoanStatus               NaN
Name: LoanID_3, dtype: object

In [37]:
lending_co_data.loc['LoanID_3', 'Region']

'Region 3'

In [38]:
lending_co_data['Location']

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [39]:
lending_co_data.loc['Location']

KeyError: 'Location'

In [40]:
lending_co_data.loc[:,'Location']

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [41]:
lending_co_data.loc[:,'Locations']

KeyError: 'Locations'