## Importing and Organizing Your Data in Python - Part IV

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Import the 'example 01' file you created in the previous lecture and set the 'Date' column as an index of that table.
Remember that there are two possible answers to this question.

In [4]:
import pandas as pd

mydata = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/04_PythonForFinance/Exercise/new_data.csv')
mydata.head()

                   timestamp    AAPL    MSFT     XOM     BP
0  2024-06-03 04:00:00+00:00  194.03  413.52  114.45  36.40
1  2024-06-04 04:00:00+00:00  194.35  416.07  112.67  35.56
2  2024-06-05 04:00:00+00:00  195.87  424.01  113.12  35.33
3  2024-06-06 04:00:00+00:00  194.48  424.52  113.97  35.45
4  2024-06-07 04:00:00+00:00  196.89  423.85  112.75  35.26

In [7]:
mydata = mydata.set_index('timestamp')
mydata.head()

                             AAPL    MSFT     XOM     BP
timestamp
2024-06-03 04:00:00+00:00  194.03  413.52  114.45  36.40
2024-06-04 04:00:00+00:00  194.35  416.07  112.67  35.56
2024-06-05 04:00:00+00:00  195.87  424.01  113.12  35.33
2024-06-06 04:00:00+00:00  194.48  424.52  113.97  35.45
2024-06-07 04:00:00+00:00  196.89  423.85  112.75  35.26

In [8]:
mydata_2 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/04_PythonForFinance/Exercise/new_data.csv',
                       index_col= 'timestamp')
mydata_2.head()

                             AAPL    MSFT     XOM     BP
timestamp
2024-06-03 04:00:00+00:00  194.03  413.52  114.45  36.40
2024-06-04 04:00:00+00:00  194.35  416.07  112.67  35.56
2024-06-05 04:00:00+00:00  195.87  424.01  113.12  35.33
2024-06-06 04:00:00+00:00  194.48  424.52  113.97  35.45
2024-06-07 04:00:00+00:00  196.89  423.85  112.75  35.26